permalink: pretty
markdown: redcarpet
pygments: true

exclude: ["CNAME", "README", "Gemfile", "Gemfile.lock", "Procfile", "config.rb", "sass"]

title: Gowalla Engineering
url: http://engineering.gowalla.com

team:
  -
    id: ak
    name: "Adam Keys"
    description: "Telling a joke and/or making Gowalla code."
    gowalla: therealadam
    github: therealadam
    twitter: therealadam

  -
    id: jc
    name: "John Critz"
    description: "Platform developer and NERF expert."
    gowalla: jc
    github: critzjm
    twitter: critzjm

  -
    id: ad
    name: "Andrew Dupont"
    description: "JavaScript sniper. Sugar-Free Red Bull addict. Gowalla developer."
    gowalla: savetheclocktower
    github: savetheclocktower
    twitter: andrewdupont

  -
    id: am
    name: "Adam McManus"
    description: "I like to ride my bike. Lots."
    gowalla: amcmanus
    github: amcmanus
    twitter: amcmanus

  -
    id: mt
    name: "Mattt Thompson"
    description: "Hacker from the Rustbelt, living in Austin, TX. iOS and Ruby Developer at Gowalla"
    gowalla: mattt
    github: mattt
    twitter: mattt

  -
    id: rs
    name: "Richard Schneeman"
    description: "A location based ruby hacker working for Gowalla."
    gowalla: schneems
    github: schneems
    twitter: schneems

  -
    id: kl
    name: "Kevin Lord"
    description: "All around tech geek, movie lover, and iOS Developer / Operations Engineer @ Gowalla."
    gowalla: lordkev
    github: lordkev
    twitter: lordkev

  -
    id: sco
    name: "Scott Raymond"
    description: "Co-founder & CTO of Gowalla. Ruby, Cocoa, & JavaScript developer. Author. Indoorsman."
    gowalla: sco
    github: sco
    twitter: sco

  -
    id: soop
    name: "Adam Michela"
    description: "I design at Gowalla, ride bicycles, and raise a couple of awesome kids. How about you?"
    gowalla: soopa
    github: soopa
    twitter: soopa

  -
    id: bf
    name: "Brad Fults"
    description: "Ruby and Rails platform developer with a background in JavaScript and front-end web development. Prefers simplicity, directness, red wine, fast cars and is healthily obsessed with quality."
    gowalla: h3h
    github: h3h
    twitter: h3h

  -
    id: pm
    name: "Philip McAllister"
    description: "Android developer @ Gowalla."
    gowalla: mcalliph
    github: mcalliph
    twitter: mcalliph

  -
    id: tp
    name: "Thorben Pimke"
    description: "BlackBerry Developer at Gowalla."
    gowalla: tprimke
    github: thorbenprimke
    twitter: tprimke

  -
    id: dy
    name: "Drew Yeaton"
    description: "Designer at Gowalla. I have 4 limbs dedicated to the eventual procreation of a progenitor species. I eat on a daily basis and play piano nightly."
    gowalla: xeeton
    github: drewyeaton
    twitter: xeeton

